# Generated by Django 2.1.2 on 2018-11-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20181103_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagetemp',
            new_name='image',
        ),
    ]
